ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - serverless-prune-plugin
  - husky
  - if-env
  - '@swc/core'
  - '@swc/jest'
  - rhachet
  - rhachet-brains-anthropic
  - rhachet-brains-xai
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - tsx
  - "@src/*"
  - "@src/.*"
  - tsc-alias
  - "@playwright/test"
